// <auto-generated/>

namespace Microsoft.Teams.Apps.AskHR.Configuration
{
    using Microsoft.Teams.Apps.AskHR.Common.Providers;
    using System.Configuration;

    /// <summary>
    /// Mvc Application
    /// </summary>
    public class MvcApplication : System.Web.HttpApplication
    {
        private IHelpDataProvider helpDataProvider;
        internal void Application_Start()
        {
            helpDataProvider = new HelpDataProvider(ConfigurationManager.AppSettings["StorageConnectionString"]);
            helpDataProvider.StoreOrUpdateFileAsync(System.Web.HttpContext.Current.Server.MapPath("./Images/"));
        }
    }
}