//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.AskHR.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.AskHR.Configuration.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask an expert.
        /// </summary>
        public static string BotCommandAskAnExpert {
            get {
                return ResourceManager.GetString("BotCommandAskAnExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with an expert.
        /// </summary>
        public static string BotCommandAskAnExpertDescription {
            get {
                return ResourceManager.GetString("BotCommandAskAnExpertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share feedback.
        /// </summary>
        public static string BotCommandShare_Feedback {
            get {
                return ResourceManager.GetString("BotCommandShare Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string BotCommandShareFeedbackDescription {
            get {
                return ResourceManager.GetString("BotCommandShareFeedbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        public static string BotCommandTakeATour {
            get {
                return ResourceManager.GetString("BotCommandTakeATour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour of key features.
        /// </summary>
        public static string BotCommandTakeATourDescription {
            get {
                return ResourceManager.GetString("BotCommandTakeATourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ComposeExtensionCommandParameter {
            get {
                return ResourceManager.GetString("ComposeExtensionCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string ComposeExtensionsCommandAssigned {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search requests assigned to an expert.
        /// </summary>
        public static string ComposeExtensionsCommandAssignedDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandAssignedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string ComposeExtensionsCommandRecent {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search recent requests.
        /// </summary>
        public static string ComposeExtensionsCommandRecentDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandRecentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string ComposeExtensionsCommandUnassigned {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search unassigned requests not yet assigned to an expert.
        /// </summary>
        public static string ComposeExtensionsCommandUnassignedDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandUnassignedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I&apos;m your friendly Q&amp;A bot. You can ask me questions, and I&apos;ll do my best to answer. If I can&apos;t help, I&apos;ll connect you to an expert.
        ///
        ///My key features:
        ///
        ///* Ask a question, get an answer
        ///* Ask an expert
        ///* Share feedback.
        /// </summary>
        public static string DefaultHelpTabText {
            get {
                return ResourceManager.GetString("DefaultHelpTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I&apos;m your friendly Q&amp;A bot. You can ask me questions, and I&apos;ll do my best to answer. If I can&apos;t help, I&apos;ll connect you to an expert.
        ///
        ///You can ask the following questions:
        ///* How do you work?
        ///* Which benefits are available?
        ///* What things are available here right now?.
        /// </summary>
        public static string DefaultWelcomeMessage {
            get {
                return ResourceManager.GetString("DefaultWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A friendly Q&amp;A bot. If it can&apos;t find an answer, it&apos;ll offer to put you in touch with an expert from human resources..
        /// </summary>
        public static string EndUserManifestFullDescription {
            get {
                return ResourceManager.GetString("EndUserManifestFullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Support.
        /// </summary>
        public static string EndUserManifestName {
            get {
                return ResourceManager.GetString("EndUserManifestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A friendly HR Support bot that answers questions and connects you to experts..
        /// </summary>
        public static string EndUserManifestShortDescription {
            get {
                return ResourceManager.GetString("EndUserManifestShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Support.
        /// </summary>
        public static string EndUserTabName {
            get {
                return ResourceManager.GetString("EndUserTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide text which will be displayed in Help tab of the bot and then click on Ok to add or Edit to modify.
        /// </summary>
        public static string HelpTabTextToolTipHoverMessage {
            get {
                return ResourceManager.GetString("HelpTabTextToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid knowledgebase Id which will be used by bot and then click on Ok to add or Edit to modify.
        /// </summary>
        public static string KnowledgeBaseToolTipHoverMessage {
            get {
                return ResourceManager.GetString("KnowledgeBaseToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A friendly Q&amp;A bot. If it can&apos;t find an answer, it&apos;ll offer to put you in touch with an expert from human resources..
        /// </summary>
        public static string SmeManifestFullDescription {
            get {
                return ResourceManager.GetString("SmeManifestFullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Support (Experts Team).
        /// </summary>
        public static string SmeManifestName {
            get {
                return ResourceManager.GetString("SmeManifestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A friendly HR Support bot that answers questions and connects you to experts..
        /// </summary>
        public static string SmeManifestShortDescription {
            get {
                return ResourceManager.GetString("SmeManifestShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Support.
        /// </summary>
        public static string StaticTabHRSupport {
            get {
                return ResourceManager.GetString("StaticTabHRSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a team Id deeplink which will be used by bot and then click on Ok to add or Edit to modify.
        /// </summary>
        public static string TeamIdToolTipHoverMessage {
            get {
                return ResourceManager.GetString("TeamIdToolTipHoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a welcome message which will be used by bot and then click on Ok to add or Edit to modify.
        /// </summary>
        public static string WelcomeMessageToolTipHoverMessage {
            get {
                return ResourceManager.GetString("WelcomeMessageToolTipHoverMessage", resourceCulture);
            }
        }
    }
}
