//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.AskHR.Configuration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.AskHR.Configuration.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided knowledge base ID is not valid..
        /// </summary>
        internal static string InvalidKnowledgeBaseId {
            get {
                return ResourceManager.GetString("InvalidKnowledgeBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided team ID is not valid..
        /// </summary>
        internal static string TeamIdValidMessage {
            get {
                return ResourceManager.GetString("TeamIdValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to save the help tab text due to an internal error. Try again..
        /// </summary>
        internal static string UnableToSaveHelpText {
            get {
                return ResourceManager.GetString("UnableToSaveHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to save the knowledge base ID due to an internal error. Try again..
        /// </summary>
        internal static string UnableToSaveKnowledgeBaseId {
            get {
                return ResourceManager.GetString("UnableToSaveKnowledgeBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to save the QnAMaker endpoint key due to an internal error. Try again..
        /// </summary>
        internal static string UnabletoSaveQnAKey {
            get {
                return ResourceManager.GetString("UnabletoSaveQnAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to save the team ID due to an internal error. Try again..
        /// </summary>
        internal static string UnableToSaveTeamId {
            get {
                return ResourceManager.GetString("UnableToSaveTeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to save the welcome message due to an internal error. Try again..
        /// </summary>
        internal static string UnableToSaveWelcomeMsg {
            get {
                return ResourceManager.GetString("UnableToSaveWelcomeMsg", resourceCulture);
            }
        }
    }
}
